### ISSUE TITLE
Error dowloading seq-core50 dataset

### ISSUE THREAD

**Issue by bhat-prashant** [hastings24/rethinking_er#9]
I am trying to reproduce the results on seq-core50. However, I get the following error while downloading the dataset:

Files already downloaded and verified
Downloading dataset
Downloading 1rm2gE74AeEXaHRP8tHvtYnmokZ5Td-Yb into ./output/mammoth/CORE50/core-50-processed.zip... Done.
/volumes1/sofwares/anaconda3/envs/mammoth/lib/python3.7/site-packages/google_drive_downloader/google_drive_downloader.py:78: UserWarning: Ignoring `unzip` since "1rm2gE74AeEXaHRP8tHvtYnmokZ5Td-Yb" does not look like a valid zip file
  warnings.warn('Ignoring `unzip` since "{}" does not look like a valid zip file'.format(file_id))
Traceback (most recent call last):
  File "/volumes1/projects/mammothssl/main.py", line 131, in <module>
    main()
  File "/volumes1/projects/mammothssl/main.py", line 124, in main
    train(model, dataset, args)
  File "/volumes1/projects/mammothssl/utils/training.py", line 111, in train
    _, _ = dataset_copy.get_data_loaders()
  File "/volumes1/projects/mammothssl/datasets/seq_core50.py", line 169, in get_data_loaders
    train=True, download=True, transform=transform)
  File "/volumes1/projects/mammothssl/datasets/seq_core50.py", line 127, in __init__
    root, train, transform, target_transform, download)
  File "/volumes1/projects/mammothssl/datasets/seq_core50.py", line 66, in __init__
    ('train' if self.train else 'test', num))))
  File "/volumes1/sofwares/anaconda3/envs/mammoth/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './output/mammoth/CORE50/processed/y_train_00.npy'
Unzipping...
Process finished with exit code 1

Please help resolve this issue.

**Comment by nktoan** [comment]
hi @hastings24 , could you reupload please the CoRe50 dataset on Drive? Many thanks!

**Comment by mbosc** [comment]
Sorry for the delay,
I updated seq_core50.py with a new link.
Best.
